name: disorder-diffusion
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia

dependencies:

  # Numerical & scientific
  - numpy
  - scipy

  # Plotting
  - matplotlib

  # Misc tools
  - pip
  
  - python=3.11
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.4
  # Add your other dependencies below
  - pip:
      # If your project is installed as a package
      # - -e .
      # Or list any pure-pip deps that are not available on conda
      # - some-extra-package